[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Brought to you by <a class="text-muted" href="https://github.com/ringsaturn/">ringsaturn</a>, Powered by <a class="text-muted" href="https://getdoks.org">Doks</a> & <a class="text-muted" href="https://gohugo.io">Hugo</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'
